### ISSUE TITLE
Problems playing local coop (can't get 2 controllers to work)

### ISSUE THREAD

**Issue by jp615** [djoslin0/sm64ex-coop#128]
I'm having a controller issue when trying to play SM64excoop (locally). I'm using Nucleus Coop. I have 2 PS3 controllers. I'm using SCP software so the pc recognizes them as xbox 360 controllers. And every time I run Nucleus (trying to play split screen local coop), 2p controller controls both screens. Also, even if I just run one solo instance of sm64excoop on its own without Nucleus, and both controllers are connected, the 2p controller will control the game, so I think that's worth noting too. I posted about it in the Nucleus Coop forum, but I'm not even sure this is a Nucleus issue, considering the problem that happens when running a solo instance as I just mentioned. This is driving me crazy lol. I've tried so many work-arounds and searched for answers and I'm getting nowhere. I've tried recompiling multiple times, uninstalling/reinstalling my SCP software, going through multiple versions of nucleus, made sure Norton data protection was off because it was prohibiting access to an input .inf file and I kept having to exclude the process when I tried multiple versions of Nucleus. At the start of the compiling screen it says to disable Norton because it could mess up the install somehow. But I've selected all the relevant folders to exclude from scanning, real-time protection, data protection, etc. so I hope that is sufficient because you can't fully disable Norton, you would have to completely uninstall it and I don't want to do that. HELP LOL. I really want to play this game!!! I've seen posts of other people experiencing the same issue, but nobody has come up with a resolution for it. The people with this problem always report that if they have multiple controllers connected, the last place controller always controls both screens. I've read from a user that he tested out other games using Nuleus and they worked fine, it was just SM64 PCport that had this issue.  Is anybody else having this same issue? If so, have you figured out why and what to do about it? Am I making some sort of compiling error?  Everything else seems to be working fine with the game, when ran by itself and when using Nucleus coop.  Please let me know if you guys figure out any answers thanks!!

**Comment by W3bsterr** [comment]
This was a scripting problem with the nucleus script as the script was made for an older version of SM64EX-COOP its should have been fixed now

**Comment by jp615** [comment]
Hey thanks for your reply.  I downloaded the new Nucleus version and got everything installed.  This is still not working for me though.  Now I can't get the 1p controller to work at all.  The reddit page for SM64pc has detailed instructions on how to start everything with the new version of Nucleus, to get both controllers to operate properly.  I followed the instructions carefully, but in this case I still couldn't get 1p controller to work.  It just doesn't do anything, no response at all to any inputs.  Pressing the end key and locking/unlocking inputs doesn't help.  I feel like I'm the only person that can't get this game to work at this point lol.  I'm using two PS3 controllers, with SCP software to emulate XBox 360 controllers.  I mean is it my controller emulation software?  I don't understand why only one controller would work if that were the case, but I'm at a loss.  Thanks so much if you can help.

**Comment by jp615** [comment]
Hey thanks for your reply.  I downloaded the new Nucleus version and got everything installed.  This is still not working for me though.  Now I can't get the 1p controller to work at all.  The reddit page for SM64pc has detailed instructions on how to start everything with the new version of Nucleus, to get both controllers to operate properly.  I followed the instructions carefully, but in this case I still couldn't get 1p controller to work.  It just doesn't do anything, no response at all to any inputs.  Pressing the end key and locking/unlocking inputs doesn't help.  I feel like I'm the only person that can't get this game to work at this point lol.  I'm using two PS3 controllers, with SCP software to emulate XBox 360 controllers.  I mean is it my controller emulation software?  I don't understand why only one controller would work if that were the case, but I'm at a loss.  Thanks so much if you can help.

**Comment by jp615** [comment]
So I wanted to explain a little more clearly my complication, and the solution I found, for those experiencing similar problems. First of all I want to spell out a little more clearly the conditions for connecting 2 controllers. The game script info that appears in Nucleus when you select the game says "In the latest version, the game is coded to only receive input from the last connected gamepad, so to restrict the gamepad xinput you have to use a workaround: for 2 players turn off the second connected gamepad before the first instance opens, after the first instance opens it should be controllable with the first gamepad, next turn on the second connected gamepad and open the second instance using the Nucleus prompt and the second gamepad should control the second instance." So to spell it out, only because this is a very specific and finnicky process...

    connect both controllers

    start up Nucleus, setup your screen options and assign both of your controllers to the window slots, select the specific game options you want to start with, then hit play

    this is the crucial part, and where I had most of my issues, BEFORE you start the handler, the second pad NEEDS to be off. It is crucial that the second pad is off before starting the handler to set up player 1

Now, the reason I was having so much difficulty is because of 2 issues. Issue #1, my controllers were connected via bluetooth, and even turning off my 2p controller literally right after I would press ok for my UAC prompt to start the handler, (because I had to hold and long press the shoulder buttons and PS button), wasn't quick enough. Issue #2, my specific controller emulation software, SCP toolkit (takes PS3 and PS4 controllers and emulates XBOX 360 controlllers, aka emulates xinput), has a setting in its configuration called "always unplug virtual controller", because as it states in the dialog box pertaining to that option "the default behavior of the virtual Xbox 360 controller device created by the virtual bus is to linger in a connected state even if the physical gamepad gets disconnected." So even when I was "turning off" my 2p controller, it was still being recognized as connected by Nucleus, which was why I couldn't get 1p to work.

Now, even when I selected the "always unplug virtual controller option", I still had to get the timing right when I was disconnecting 2p. So I realized what worked the best is to set up everything as I outlined above, press play, and on my computer I get a UAC prompt before starting the first handler, THAT is when I disconnect 2p controller. AFTER disconnecting 2p THEN press ok on the prompt to start the handler. Proceed to configure player1 the way you like and host, then connect 2p controller, and then start your 2nd instance AFTER 2p controller is connected, then join. And yes, the timing is very specific, which is why I'm trying to outline all this as clearly as possible. Sorry for the lengthy response, I just wanted to help anyone else who might experience such an obscure complication. I'm not familiar with any other controller emulation software because this is all I need for what I have, but for anyone else using similar software who is also experiencing problems like I described connecting 2 controllers, check your settings to see if your software does the same thing regarding disconnected controllers lingering in a connected state. Hope this helps.

**Comment by jp615** [comment]
Just wanted to make sure to add that this solution was applicable to Nucleus Coop v2.0
