### ISSUE TITLE
Linking fails on Raspberry Pi 4 (aarch64)

### ISSUE THREAD

**Issue by vanfanel** [djoslin0/sm64ex-coop#157]
Hi there,

Sm64ex-coop builds fine, but it can't link because the build system tries to link against included libs in `/libs/bass`, look:
```
/usr/bin/ld: skipping incompatible build/us_pc/libbass.so when searching for -lbass
/usr/bin/ld: cannot find -lbass
/usr/bin/ld: skipping incompatible build/us_pc/libbass.so when searching for -lbass
/usr/bin/ld: skipping incompatible build/us_pc/libbass_fx.so when searching for -lbass_fx
/usr/bin/ld: cannot find -lbass_fx
/usr/bin/ld: skipping incompatible build/us_pc/libbass_fx.so when searching for -lbass_fx
```
These libs seem to be x86_64 and x86 only :(

The same seems to happen with liblua53.a:

```
/usr/bin/ld: skipping incompatible lib/lua/linux/liblua53.a when searching for -l:liblua53.a
/usr/bin/ld: skipping incompatible lib/lua/linux/liblua53.a when searching for -l:liblua53.a
/usr/bin/ld: cannot find -l:liblua53.a
/usr/bin/ld: skipping incompatible lib/lua/linux/liblua53.a when searching for -l:liblua53.a
/usr/bin/ld: skipping incompatible lib/lua/linux/liblua53.a when searching for -l:liblua53.a

```

I guess those should be 3rd party deps, cloned via something like `git submodule update --init` and built along with the rest of the project, because including x86_64 and x86 versions of the libs and link against that doesn't make much sense, does it?

I would also gladly build without libass anyway, sm64ex doesn't have that dep and I don't miss it. Maybe it could be optional like many other features?

**Comment by Beyley** [comment]
> Hi there,
> 
> Sm64ex-coop builds fine, but it can't link because the build system tries to link against included libs in `/libs/bass`, look:
> 
> ```
> /usr/bin/ld: skipping incompatible build/us_pc/libbass.so when searching for -lbass
> /usr/bin/ld: cannot find -lbass
> /usr/bin/ld: skipping incompatible build/us_pc/libbass.so when searching for -lbass
> /usr/bin/ld: skipping incompatible build/us_pc/libbass_fx.so when searching for -lbass_fx
> /usr/bin/ld: cannot find -lbass_fx
> /usr/bin/ld: skipping incompatible build/us_pc/libbass_fx.so when searching for -lbass_fx
> ```
> 
> These libs seem to be x86_64 and x86 only :(
> 
> The same seems to happen with liblua53.a:
> 
> ```
> /usr/bin/ld: skipping incompatible lib/lua/linux/liblua53.a when searching for -l:liblua53.a
> /usr/bin/ld: skipping incompatible lib/lua/linux/liblua53.a when searching for -l:liblua53.a
> /usr/bin/ld: cannot find -l:liblua53.a
> /usr/bin/ld: skipping incompatible lib/lua/linux/liblua53.a when searching for -l:liblua53.a
> /usr/bin/ld: skipping incompatible lib/lua/linux/liblua53.a when searching for -l:liblua53.a
> ```
> 
> I guess those should be 3rd party deps, cloned via something like `git submodule update --init` and built along with the rest of the project, because including x86_64 and x86 versions of the libs and link against that doesn't make much sense, does it?
> 
> I would also gladly build without libass anyway, sm64ex doesn't have that dep and I don't miss it. Maybe it could be optional like many other features?

What standard ex requires has nothing to do with what we require

We do _require_ Bass for mods, no linux ARM binaries should be fixed in the next release

**Comment by vanfanel** [comment]
> > Hi there,
> > Sm64ex-coop builds fine, but it can't link because the build system tries to link against included libs in `/libs/bass`, look:
> > ```
> > /usr/bin/ld: skipping incompatible build/us_pc/libbass.so when searching for -lbass
> > /usr/bin/ld: cannot find -lbass
> > /usr/bin/ld: skipping incompatible build/us_pc/libbass.so when searching for -lbass
> > /usr/bin/ld: skipping incompatible build/us_pc/libbass_fx.so when searching for -lbass_fx
> > /usr/bin/ld: cannot find -lbass_fx
> > /usr/bin/ld: skipping incompatible build/us_pc/libbass_fx.so when searching for -lbass_fx
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > These libs seem to be x86_64 and x86 only :(
> > The same seems to happen with liblua53.a:
> > ```
> > /usr/bin/ld: skipping incompatible lib/lua/linux/liblua53.a when searching for -l:liblua53.a
> > /usr/bin/ld: skipping incompatible lib/lua/linux/liblua53.a when searching for -l:liblua53.a
> > /usr/bin/ld: cannot find -l:liblua53.a
> > /usr/bin/ld: skipping incompatible lib/lua/linux/liblua53.a when searching for -l:liblua53.a
> > /usr/bin/ld: skipping incompatible lib/lua/linux/liblua53.a when searching for -l:liblua53.a
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I guess those should be 3rd party deps, cloned via something like `git submodule update --init` and built along with the rest of the project, because including x86_64 and x86 versions of the libs and link against that doesn't make much sense, does it?
> > I would also gladly build without libass anyway, sm64ex doesn't have that dep and I don't miss it. Maybe it could be optional like many other features?
> 
> What standard ex requires has nothing to do with what we require
> 
> We do _require_ Bass for mods, no linux ARM binaries should be fixed in the next release

Do you mean next release will link on ARM because the build system will download and build libbass and liblua as part of the sm64ex-coop build process?

**Comment by Beyley** [comment]
> > > Hi there,
> > > Sm64ex-coop builds fine, but it can't link because the build system tries to link against included libs in `/libs/bass`, look:
> > > ```
> > > /usr/bin/ld: skipping incompatible build/us_pc/libbass.so when searching for -lbass
> > > /usr/bin/ld: cannot find -lbass
> > > /usr/bin/ld: skipping incompatible build/us_pc/libbass.so when searching for -lbass
> > > /usr/bin/ld: skipping incompatible build/us_pc/libbass_fx.so when searching for -lbass_fx
> > > /usr/bin/ld: cannot find -lbass_fx
> > > /usr/bin/ld: skipping incompatible build/us_pc/libbass_fx.so when searching for -lbass_fx
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > These libs seem to be x86_64 and x86 only :(
> > > The same seems to happen with liblua53.a:
> > > ```
> > > /usr/bin/ld: skipping incompatible lib/lua/linux/liblua53.a when searching for -l:liblua53.a
> > > /usr/bin/ld: skipping incompatible lib/lua/linux/liblua53.a when searching for -l:liblua53.a
> > > /usr/bin/ld: cannot find -l:liblua53.a
> > > /usr/bin/ld: skipping incompatible lib/lua/linux/liblua53.a when searching for -l:liblua53.a
> > > /usr/bin/ld: skipping incompatible lib/lua/linux/liblua53.a when searching for -l:liblua53.a
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I guess those should be 3rd party deps, cloned via something like `git submodule update --init` and built along with the rest of the project, because including x86_64 and x86 versions of the libs and link against that doesn't make much sense, does it?
> > > I would also gladly build without libass anyway, sm64ex doesn't have that dep and I don't miss it. Maybe it could be optional like many other features?
> > 
> > 
> > What standard ex requires has nothing to do with what we require
> > We do _require_ Bass for mods, no linux ARM binaries should be fixed in the next release
> 
> Do you mean next release will link on ARM because the build system will download and build libbass and liblua as part of the sm64ex-coop build process?

It will be included in the repository, not downloaded at compile time

**Comment by EmeraldLoc** [comment]
I think this may be fixed in the next ver, Isaac knows more, you could also ask in the ex-coop discord server.

**Comment by Isaac0-dev** [comment]
Yeah it will be fixed in the next version.
Until then if you still want to build co-op on arm you can provide your own libraries. 
Bass libraries are available on their website and I think you'll have to compile your Lua libraries yourself. Make sure to use 5.3.5.

**Comment by Isaac0-dev** [comment]
Well the next release might not come out for a bit so its up to you. Co-op still technically doesn't have rpi support.

**Comment by djoslin0** [comment]
Should be fixed now, feel free to reopen if that isn't the case

**Comment by vanfanel** [comment]
@djoslin0 The issue is still not fixed for arm64 (aarch64): I can see there's `lib/lua/linux/liblua53-arm.a` but that's for 32bit arm only, but the Raspberry Pi runs both 32 and 64bit GNU/Linux distros. 
Can you please include a 64bit liblua or use the system-installed liblua instead of forcing a precompiled lib?
