### ISSUE TITLE
White Screen with Stuttering Audio; Game is not playable

### ISSUE THREAD

**Issue by Superjustinbros** [djoslin0/sm64ex-coop#187]
**Describe the bug**
Earlier today, all of my attempts to launch sm64ex-coop have resulted in a completely white screen being displayed in place of actual gameplay.

**To Reproduce**
1. Compile the game with OpenGL and start it up
2. The game will not transition to the main menu with Mario in the courtyard, and will remain paused on a blank white screen while the game's audio plays at ~1FPS.
3. If compiled with DirectX, the screen will still be blank, but it will be black instead of white.

**Expected behavior**
The game would boot normally, as it did for me for some time.

**Screenshots**
![image](https://user-images.githubusercontent.com/4167951/214411362-0d86cfe1-6de3-4adc-8d7d-1bc7cd905c45.png)

**Desktop**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Beta 30.0

**Additional context**
The game previously worked until today, and I am unable to decider what I could have done to my computer that prevents the game from launching in any capacity. I did install a VPN program (Hamachi) at the recommendation of a friend of mine in order to play multiplayer, though uninstalling it after sm64ex-coop initially stopped working does not fix the issues I am having.

**Comment by Superjustinbros** [comment]
Turns out the issue was solved by simply unplugging the 8bitdo controller I had plugged into my computer and it now works like a charm.

**Comment by djoslin0** [comment]
I've looked into this several times, but I can't explain why Windows causes this. I've even seen the gamepad configuration program that Windows includes in the OS hang in this scenario, so I'm not sure what I can do. Seems like a Windows issue

**Comment by mr-sihc** [comment]
oh this is the outdated rumble API from SDL2


i updated it to a more recent version and it fixed it, but this is not fixed here
